
version: '3'

services:

  #
  # Get into this container with:
  #
  # docker-compose exec testing sh
  #
  testing:
    build:
      context: .
      dockerfile: files/Dockerfile-testing
    volumes:
      - .:/mnt
      - ./files/dummy-ssh-keys/testing.key:/testing.key
      - ./files/testing-ssh-config:/root/.ssh/config
      - ./files/testing-motd:/etc/motd

  source:
    # 
    # Docs for this excelent container available at:
    # 
    # https://github.com/panubo/docker-sshd
    # 
    build:
      context: .
      dockerfile: files/Dockerfile-source

    volumes:
      - .:/mnt
      - ./files/dummy-ssh-keys/testing.pub:/root/.ssh/authorized_keys
      - ./files/source-motd:/etc/motd

    environment:
      - SSH_ENABLE_ROOT=true

  source-netcat-openbsd:

    build:
      context: .
      dockerfile: files/Dockerfile-source-netcat-openbsd

    volumes:
      - .:/mnt
      - ./files/dummy-ssh-keys/testing.pub:/root/.ssh/authorized_keys
      - ./files/source-motd:/etc/motd

    environment:
      - SSH_ENABLE_ROOT=true

  source-centos:

    build:
      context: .
      dockerfile: files/Dockerfile-source-centos

    volumes:
      - .:/mnt
      - ./files/dummy-ssh-keys/testing.pub:/root/.ssh/authorized_keys
      - ./files/source-centos-motd:/etc/motd
      - ./files/source-centos-sshd-config:/etc/ssh/sshd_config:ro

# TODO: Delete?
    environment:
      - SSH_ENABLE_ROOT=true

  source-ubuntu:

    build:
      context: .
      dockerfile: files/Dockerfile-source-ubuntu

    volumes:
      - .:/mnt
      - ./files/dummy-ssh-keys/testing.pub:/root/.ssh/authorized_keys
      - ./files/source-ubuntu-motd:/etc/motd
      - ./files/source-centos-sshd-config:/etc/ssh/sshd_config:ro

# TODO: Delete?
    environment:
      - SSH_ENABLE_ROOT=true

  source-ubuntu-openbsd:

    build:
      context: .
      dockerfile: files/Dockerfile-source-ubuntu-openbsd

    volumes:
      - .:/mnt
      - ./files/dummy-ssh-keys/testing.pub:/root/.ssh/authorized_keys
      - ./files/source-ubuntu-openbsd-motd:/etc/motd
      - ./files/source-centos-sshd-config:/etc/ssh/sshd_config:ro

# TODO: Delete?
    environment:
      - SSH_ENABLE_ROOT=true



  dest01: 
    build:
      context: .
      dockerfile: files/Dockerfile-dest

    cap_add:
      - NET_ADMIN

    volumes:
      - .:/mnt
      - ./files/dest-motd:/etc/motd
      - ./files/dest-nginx-default.conf:/etc/nginx/conf.d/default.conf



